spring.application.name=Autos Colombia
# Configuración de la Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/parqueadero_autoscolombia?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=NuevaClave2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect